# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nukds',
                'doc_host': 'https://santosh-rajan.github.io',
                'git_url': 'https://github.com/santosh-rajan/nukds',
                'lib_path': 'nukds'},
  'syms': {'nukds.core': {'nukds.core.foo': ('core.html#foo', 'nukds/core.py')}}}
