# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nukds',
                'doc_host': 'https://santosh-rajan.github.io',
                'git_url': 'https://github.com/santosh-rajan/nukds',
                'lib_path': 'nukds'},
  'syms': { 'nukds.bigquery': { 'nukds.bigquery.create_client': ('bigquery.html#create_client', 'nukds/bigquery.py'),
                                'nukds.bigquery.query_to_dataframe': ('bigquery.html#query_to_dataframe', 'nukds/bigquery.py')},
            'nukds.core': {'nukds.core.foo': ('core.html#foo', 'nukds/core.py')}}}
