# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_bigquery.ipynb.

# %% auto 0
__all__ = ['query_to_dataframe', 'create_client']

# %% ../nbs/00_bigquery.ipynb 3
from google.cloud import bigquery

# %% ../nbs/00_bigquery.ipynb 5
def query_to_dataframe(bq_client: bigquery.Client, sql: str) -> pd.DataFrame:
    """
    Query -> DataFrame
    """
    dataframe = bq_client.query(sql).to_dataframe()

    return dataframe

# %% ../nbs/00_bigquery.ipynb 8
def create_client(
    auth_scopes: [str] = [],  # eg: ["bigquery", "drive"]
):
    """Create a BigQuery client with the given auth scopes."""
    if len(auth_scopes) == 0:
        return bigquery.Client()
    else:
        # to pull files from drive or other services, we need to authenticate
        import google.auth
        credentials, project = google.auth.default(
            [f"https://www.googleapis.com/auth/{service}" for service in []]
        )
        return bigquery.Client(
            credentials=credentials,
            project=project,
        )
